In [2]:
import numpy as np
np.__version__

'1.14.6'

In [3]:
narray=np.array([10, 10, 20, 30, 0]).all()
if narray == True:
    print('Numpy array doesn\'t have a zero value')
else:
    print('Numpy array has a zero value')

Numpy array has a zero value


In [4]:
arr1=np.array([45, 67, 23])
arr2=np.array([56, 23, 89])

greater_check=np.greater(arr1, arr2)
print(greater_check)
greater_equal_check=np.greater_equal(arr1, arr2)
print(greater_equal_check)
less_check=np.less(arr1, arr2)
print(less_check)
less_equal_check=np.less_equal(arr1, arr2)
print(less_equal_check)

[False  True False]
[False  True False]
[ True False  True]
[ True False  True]


In [5]:
zeroarr=np.zeros(8)
onearr=np.ones(5)
tenfivearr=np.repeat(5, 10)
arr=np.array([zeroarr, onearr, tenfivearr])
arr

array([array([0., 0., 0., 0., 0., 0., 0., 0.]),
       array([1., 1., 1., 1., 1.]), array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])],
      dtype=object)

In [6]:
vector=np.array([2, 0, 2])
matrix=np.array([[23, 45, 11], [12, 23, 54], [29, 19, 34], [1, 23, 10]]) 
print('vector', vector)
print('matrix ', matrix)
print('vector + matrix ', vector+matrix)

vector [2 0 2]
matrix  [[23 45 11]
 [12 23 54]
 [29 19 34]
 [ 1 23 10]]
vector + matrix  [[25 45 13]
 [14 23 56]
 [31 19 36]
 [ 3 23 12]]


In [7]:
onearr=np.ones((5, 5))
print(onearr)
onearr[1:4,1:4]=25
print(onearr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 1.  1.  1.  1.  1.]
 [ 1. 25. 25. 25.  1.]
 [ 1. 25. 25. 25.  1.]
 [ 1. 25. 25. 25.  1.]
 [ 1.  1.  1.  1.  1.]]


In [8]:
arr1=np.array([23, 45, 11, 5])
arr2=np.array([23, 5, 1])
np.intersect1d(arr1, arr2)

array([ 5, 23])

In [9]:
arr1=np.array([[23, 45, 11],[12, 23, 54],[1, 23, 10]])
arr2=np.array([[3, 5, 1],[2, 3, 4],[9, 1, 5]])
ahstack=np.hstack((arr1, arr2))
print('hstack: ', ahstack)
avstack=np.vstack((arr1, arr2))
print('vstack: ', avstack)
ahsplit1, ahsplit2, ahsplit3=np.split(arr1, [1,2], axis=0)
print('Row 1: ', ahsplit1)
print('Row 2: ', ahsplit2)
print('Row 3: ', ahsplit3)
avsplit1, avsplit2, avsplit3=np.split(arr1, [1,2], axis=1)
print('Column 1: ', avsplit1)
print('Column 2: ', avsplit2)
print('Column 3: ', avsplit3)

hstack:  [[23 45 11  3  5  1]
 [12 23 54  2  3  4]
 [ 1 23 10  9  1  5]]
vstack:  [[23 45 11]
 [12 23 54]
 [ 1 23 10]
 [ 3  5  1]
 [ 2  3  4]
 [ 9  1  5]]
Row 1:  [[23 45 11]]
Row 2:  [[12 23 54]]
Row 3:  [[ 1 23 10]]
Column 1:  [[23]
 [12]
 [ 1]]
Column 2:  [[45]
 [23]
 [23]]
Column 3:  [[11]
 [54]
 [10]]


In [10]:
import pandas as pd

assessment_results = {'name': ['Anastasia', 'Paul', 'Kathe', 'Joseph', 'Linda', 'Michael', 'Matt',
'Laurentine', 'Chirstian', 'Jonas'],
'score': [12.5, 10, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

dataframe=pd.DataFrame(assessment_results, index=labels)
dataframe

name  score  attempts qualify
a   Anastasia   12.5         1     yes
b        Paul   10.0         3      no
c       Kathe   16.5         2     yes
d      Joseph    NaN         3      no
e       Linda    9.0         2      no
f     Michael   20.0         3     yes
g        Matt   14.5         1     yes
h  Laurentine    NaN         1      no
i   Chirstian    8.0         2      no
j       Jonas   19.0         1     yes

In [11]:
dataframe[0:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Paul   10.0         3      no
c      Kathe   16.5         2     yes

In [12]:
dataframe.loc[dataframe['attempts'] > 2]

name  score  attempts qualify
b     Paul   10.0         3      no
d   Joseph    NaN         3      no
f  Michael   20.0         3     yes

In [13]:
rows = dataframe.shape[0]
columns = dataframe.shape[1]
print('Rows: ', rows)
print('Columns: ', columns)

Rows:  10
Columns:  4


In [14]:
dataframe[(dataframe['score'] >= 14) & (dataframe['score'] <= 20)]

name  score  attempts qualify
c    Kathe   16.5         2     yes
f  Michael   20.0         3     yes
g     Matt   14.5         1     yes
j    Jonas   19.0         1     yes

In [16]:
dataframe.loc['c','attempts']=11.5
dataframe

name  score  attempts qualify
a   Anastasia   12.5       1.0     yes
b        Paul   10.0       3.0      no
c       Kathe   16.5      11.5     yes
d      Joseph    NaN       3.0      no
e       Linda    9.0       2.0      no
f     Michael   20.0       3.0     yes
g        Matt   14.5       1.0     yes
h  Laurentine    NaN       1.0      no
i   Chirstian    8.0       2.0      no
j       Jonas   19.0       1.0     yes

In [17]:
dataframe['mean_score'] = dataframe['score']/dataframe['attempts']
dataframe[['name','mean_score']]

name  mean_score
a   Anastasia   12.500000
b        Paul    3.333333
c       Kathe    1.434783
d      Joseph         NaN
e       Linda    4.500000
f     Michael    6.666667
g        Matt   14.500000
h  Laurentine         NaN
i   Chirstian    4.000000
j       Jonas   19.000000